(part "DPX167125DT-8197B1"
    (packageRef "DPX167125DT8197B1")
    (interface
        (port "1" (symbPinId 1) (portName "GND_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "COMMON_PORT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "LOW-BAND_PORT") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND_3") (portType INOUT))
        (port "6" (symbPinId 6) (portName "HIGH-BAND_PORT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "TDK")
    (property "Manufacturer_Part_Number" "DPX167125DT-8197B1")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "DPX167125DT-8197B1")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/dpx167125dt-8197b1/tdk?utm_currency=USD&region=nac")
    (property "Description" "Signal Conditioning Multilayer DPX for 2.4-2.5GHz W-LAN&BT/5-7GHz W-LAN")
    (property "Datasheet_Link" "https://www.mouser.ph/ProductDetail/TDK/DPX167125DT-8197B1?qs=iLKYxzqNS75cuGe4fWh6hg%3D%3D")
    (property "symbolName1" "DPX167125DT-8197B1")
)
