(part "6DFN36CA-M3_I"
    (packageRef "SS5N42HM3I")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "6DFN36CA-M3/I")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "ESD Protection Diodes / TVS Diodes 600W,36V 5%, DFN3820A BIDIR TVS")
    (property "Datasheet_Link" "https://www.vishay.com/docs/98490/6dfn12cathru6dfn100ca.pdf")
    (property "symbolName1" "6DFN36CA-M3_I")
)
