(part "TPS7A2118PQWDRBRQ1"
    (packageRef "SON65P300X300X100-9N-D")
    (interface
        (port "1" (symbPinId 1) (portName "OUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NC_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NC_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND_1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "EN") (portType INOUT))
        (port "6" (symbPinId 6) (portName "NC_3") (portType INOUT))
        (port "7" (symbPinId 7) (portName "NC_4") (portType INOUT))
        (port "8" (symbPinId 8) (portName "IN") (portType INOUT))
        (port "9" (symbPinId 9) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS7A2118PQWDRBRQ1")
    (property "Mouser_Part_Number" "595-7A2118PQWDRBRQ1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS7A2118PQWDRBRQ1?qs=dbcCsuKDzFX2e%252Bp94sZFQg%3D%3D")
    (property "Arrow_Part_Number" "TPS7A2118PQWDRBRQ1")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tps7a2118pqwdrbrq1/texas-instruments?utm_currency=USD&region=nac")
    (property "Description" "Linear Voltage Regulator IC Positive Fixed 1 Output 500mA 8-SON (3x3), -40C ~ 150C (TJ)")
    (property "Datasheet_Link" "https://www.ti.com/lit/gpn/tps7a21-q1")
    (property "symbolName1" "TPS7A2118PQWDRBRQ1")
)
