(part "STM32N645I0H3Q"
    (packageRef "BGA178C80P14X14_1200X1200X100")
    (interface
        (port "A1" (symbPinId 1) (portName "PDR_ON") (portType INOUT))
        (port "A2" (symbPinId 2) (portName "OTG2_HS_DM") (portType INOUT))
        (port "A3" (symbPinId 3) (portName "NC_1") (portType INOUT))
        (port "A4" (symbPinId 4) (portName "VDD33US_B") (portType INOUT))
        (port "A5" (symbPinId 5) (portName "OTG1_HS_DM") (portType INOUT))
        (port "A6" (symbPinId 6) (portName "UCPD1_C_C1") (portType INOUT))
        (port "A7" (symbPinId 7) (portName "PH1-_OSC_OU_T") (portType INOUT))
        (port "A8" (symbPinId 8) (portName "PC6") (portType INOUT))
        (port "A9" (symbPinId 9) (portName "PC7") (portType INOUT))
        (port "A10" (symbPinId 10) (portName "PE6") (portType INOUT))
        (port "A11" (symbPinId 11) (portName "PD6") (portType INOUT))
        (port "A12" (symbPinId 12) (portName "PD0") (portType INOUT))
        (port "A13" (symbPinId 13) (portName "PD3") (portType INOUT))
        (port "A14" (symbPinId 14) (portName "VSS_1") (portType INOUT))
        (port "B1" (symbPinId 15) (portName "PC14-_OSC32_I_N") (portType INOUT))
        (port "B2" (symbPinId 16) (portName "OTG2_HS_DP") (portType INOUT))
        (port "B3" (symbPinId 17) (portName "OTG1_ID") (portType INOUT))
        (port "B4" (symbPinId 18) (portName "OTG2_TX_RTUNE") (portType INOUT))
        (port "B5" (symbPinId 19) (portName "OTG1_HS_DP") (portType INOUT))
        (port "B6" (symbPinId 20) (portName "UCPD1_C_C2") (portType INOUT))
        (port "B7" (symbPinId 21) (portName "PH0-_OSC_IN") (portType INOUT))
        (port "B8" (symbPinId 22) (portName "PC1") (portType INOUT))
        (port "B9" (symbPinId 23) (portName "PE11") (portType INOUT))
        (port "B10" (symbPinId 24) (portName "PE15") (portType INOUT))
        (port "B11" (symbPinId 25) (portName "PD7") (portType INOUT))
        (port "B12" (symbPinId 26) (portName "PD1") (portType INOUT))
        (port "B13" (symbPinId 27) (portName "PD4") (portType INOUT))
        (port "B14" (symbPinId 28) (portName "PE9") (portType INOUT))
        (port "C1" (symbPinId 29) (portName "PC15-_OSC32_O_UT") (portType INOUT))
        (port "C2" (symbPinId 30) (portName "VBAT") (portType INOUT))
        (port "C3" (symbPinId 31) (portName "PC13") (portType INOUT))
        (port "C4" (symbPinId 32) (portName "NC_2") (portType INOUT))
        (port "C5" (symbPinId 33) (portName "OTG2_ID") (portType INOUT))
        (port "C6" (symbPinId 34) (portName "PC8") (portType INOUT))
        (port "C7" (symbPinId 35) (portName "PC11") (portType INOUT))
        (port "C8" (symbPinId 36) (portName "PH9") (portType INOUT))
        (port "C9" (symbPinId 37) (portName "PE14") (portType INOUT))
        (port "C10" (symbPinId 38) (portName "PE13") (portType INOUT))
        (port "C11" (symbPinId 39) (portName "PD10") (portType INOUT))
        (port "C12" (symbPinId 40) (portName "PD15") (portType INOUT))
        (port "C13" (symbPinId 41) (portName "PE8") (portType INOUT))
        (port "C14" (symbPinId 42) (portName "PE10") (portType INOUT))
        (port "D1" (symbPinId 43) (portName "V08CAP") (portType INOUT))
        (port "D2" (symbPinId 44) (portName "VFBSMP_S") (portType INOUT))
        (port "D3" (symbPinId 45) (portName "BOOT0") (portType INOUT))
        (port "D4" (symbPinId 46) (portName "VDDA18U_SB") (portType INOUT))
        (port "D5" (symbPinId 47) (portName "OTG1_TX_RTUNE") (portType INOUT))
        (port "D6" (symbPinId 48) (portName "PC9") (portType INOUT))
        (port "D7" (symbPinId 49) (portName "PC12") (portType INOUT))
        (port "D8" (symbPinId 50) (portName "PC10") (portType INOUT))
        (port "D9" (symbPinId 51) (portName "PE5") (portType INOUT))
        (port "D10" (symbPinId 52) (portName "PE12") (portType INOUT))
        (port "D11" (symbPinId 53) (portName "PE7") (portType INOUT))
        (port "D12" (symbPinId 54) (portName "PD14") (portType INOUT))
        (port "D13" (symbPinId 55) (portName "PD8") (portType INOUT))
        (port "D14" (symbPinId 56) (portName "PD5") (portType INOUT))
        (port "E1" (symbPinId 57) (portName "VDDA18P_MU") (portType INOUT))
        (port "E2" (symbPinId 58) (portName "VSSAPM_U") (portType INOUT))
        (port "E3" (symbPinId 59) (portName "PWR_ON") (portType INOUT))
        (port "E4" (symbPinId 60) (portName "NRST") (portType INOUT))
        (port "E5" (symbPinId 61) (portName "VDDA18A_ON") (portType INOUT))
        (port "E6" (symbPinId 62) (portName "PH2") (portType INOUT))
        (port "E7" (symbPinId 63) (portName "VSS_2") (portType INOUT))
        (port "E8" (symbPinId 64) (portName "VDDIO4_1") (portType INOUT))
        (port "E9" (symbPinId 65) (portName "VDDIO4_2") (portType INOUT))
        (port "E10" (symbPinId 66) (portName "PD2") (portType INOUT))
        (port "E11" (symbPinId 67) (portName "PD12") (portType INOUT))
        (port "E12" (symbPinId 68) (portName "PB3") (portType INOUT))
        (port "E13" (symbPinId 69) (portName "PB2") (portType INOUT))
        (port "E14" (symbPinId 70) (portName "PD13") (portType INOUT))
        (port "F1" (symbPinId 71) (portName "VSSSMP_S_1") (portType INOUT))
        (port "F2" (symbPinId 72) (portName "VSSSMP_S_2") (portType INOUT))
        (port "F3" (symbPinId 73) (portName "VSSSMP_S_3") (portType INOUT))
        (port "F4" (symbPinId 74) (portName "VSSSMP_S_4") (portType INOUT))
        (port "F5" (symbPinId 75) (portName "VSSAON") (portType INOUT))
        (port "F10" (symbPinId 76) (portName "VSS_3") (portType INOUT))
        (port "F11" (symbPinId 77) (portName "PD11") (portType INOUT))
        (port "F12" (symbPinId 78) (portName "PE0") (portType INOUT))
        (port "F13" (symbPinId 79) (portName "PE1") (portType INOUT))
        (port "F14" (symbPinId 80) (portName "PE2") (portType INOUT))
        (port "G1" (symbPinId 81) (portName "VLXSMPS_1") (portType INOUT))
        (port "G2" (symbPinId 82) (portName "VLXSMPS_2") (portType INOUT))
        (port "G3" (symbPinId 83) (portName "VLXSMPS_3") (portType INOUT))
        (port "G4" (symbPinId 84) (portName "VLXSMPS_4") (portType INOUT))
        (port "G10" (symbPinId 85) (portName "VDD_1") (portType INOUT))
        (port "G11" (symbPinId 86) (portName "VDD_2") (portType INOUT))
        (port "G12" (symbPinId 87) (portName "VDD_3") (portType INOUT))
        (port "G13" (symbPinId 88) (portName "PE3") (portType INOUT))
        (port "G14" (symbPinId 89) (portName "PB0") (portType INOUT))
        (port "H1" (symbPinId 90) (portName "VDDSMP_S_1") (portType INOUT))
        (port "H2" (symbPinId 91) (portName "VDDSMP_S_2") (portType INOUT))
        (port "H3" (symbPinId 92) (portName "VDDSMP_S_3") (portType INOUT))
        (port "H4" (symbPinId 93) (portName "VDDSMP_S_4") (portType INOUT))
        (port "H10" (symbPinId 94) (portName "VSS_4") (portType INOUT))
        (port "H11" (symbPinId 95) (portName "VSS_5") (portType INOUT))
        (port "H12" (symbPinId 96) (portName "PD9") (portType INOUT))
        (port "H13" (symbPinId 97) (portName "PB7") (portType INOUT))
        (port "H14" (symbPinId 98) (portName "PB6") (portType INOUT))
        (port "J1" (symbPinId 99) (portName "PF4") (portType INOUT))
        (port "J2" (symbPinId 100) (portName "PF6") (portType INOUT))
        (port "J3" (symbPinId 101) (portName "PF10") (portType INOUT))
        (port "J4" (symbPinId 102) (portName "PF5") (portType INOUT))
        (port "J5" (symbPinId 103) (portName "PF3") (portType INOUT))
        (port "J10" (symbPinId 104) (portName "VDDIO3_1") (portType INOUT))
        (port "J11" (symbPinId 105) (portName "VDDIO3_2") (portType INOUT))
        (port "J12" (symbPinId 106) (portName "PN12") (portType INOUT))
        (port "J13" (symbPinId 107) (portName "PN4") (portType INOUT))
        (port "J14" (symbPinId 108) (portName "PN8") (portType INOUT))
        (port "K1" (symbPinId 109) (portName "PF2") (portType INOUT))
        (port "K2" (symbPinId 110) (portName "PF14") (portType INOUT))
        (port "K3" (symbPinId 111) (portName "PF15") (portType INOUT))
        (port "K4" (symbPinId 112) (portName "PF7") (portType INOUT))
        (port "K5" (symbPinId 113) (portName "VSS_6") (portType INOUT))
        (port "K6" (symbPinId 114) (portName "VDDCOR_E_1") (portType INOUT))
        (port "K7" (symbPinId 115) (portName "VDDCOR_E_2") (portType INOUT))
        (port "K8" (symbPinId 116) (portName "VDDCOR_E_3") (portType INOUT))
        (port "K9" (symbPinId 117) (portName "VDDCOR_E_4") (portType INOUT))
        (port "K10" (symbPinId 118) (portName "VSS_7") (portType INOUT))
        (port "K11" (symbPinId 119) (portName "PA3") (portType INOUT))
        (port "K12" (symbPinId 120) (portName "PN6") (portType INOUT))
        (port "K13" (symbPinId 121) (portName "PN7") (portType INOUT))
        (port "K14" (symbPinId 122) (portName "PN5") (portType INOUT))
        (port "L1" (symbPinId 123) (portName "PF8") (portType INOUT))
        (port "L2" (symbPinId 124) (portName "PF11") (portType INOUT))
        (port "L3" (symbPinId 125) (portName "PF12") (portType INOUT))
        (port "L4" (symbPinId 126) (portName "VDDA18P_LL") (portType INOUT))
        (port "L5" (symbPinId 127) (portName "PG14") (portType INOUT))
        (port "L6" (symbPinId 128) (portName "PA12") (portType INOUT))
        (port "L7" (symbPinId 129) (portName "VDDCOR_E_5") (portType INOUT))
        (port "L8" (symbPinId 130) (portName "PA6") (portType INOUT))
        (port "L9" (symbPinId 131) (portName "PA1") (portType INOUT))
        (port "L10" (symbPinId 132) (portName "PB11") (portType INOUT))
        (port "L11" (symbPinId 133) (portName "PB4") (portType INOUT))
        (port "L12" (symbPinId 134) (portName "PG8") (portType INOUT))
        (port "L13" (symbPinId 135) (portName "PN2") (portType INOUT))
        (port "L14" (symbPinId 136) (portName "PN9") (portType INOUT))
        (port "M1" (symbPinId 137) (portName "VREF+") (portType INOUT))
        (port "M2" (symbPinId 138) (portName "PF13") (portType INOUT))
        (port "M3" (symbPinId 139) (portName "VDDA18A_DC") (portType INOUT))
        (port "M4" (symbPinId 140) (portName "VSSA") (portType INOUT))
        (port "M5" (symbPinId 141) (portName "PG15") (portType INOUT))
        (port "M6" (symbPinId 142) (portName "PA11") (portType INOUT))
        (port "M7" (symbPinId 143) (portName "PA9") (portType INOUT))
        (port "M8" (symbPinId 144) (portName "PA5") (portType INOUT))
        (port "M9" (symbPinId 145) (portName "PG1") (portType INOUT))
        (port "M10" (symbPinId 146) (portName "PB12") (portType INOUT))
        (port "M11" (symbPinId 147) (portName "PB5") (portType INOUT))
        (port "M12" (symbPinId 148) (portName "PG0") (portType INOUT))
        (port "M13" (symbPinId 149) (portName "PN0") (portType INOUT))
        (port "M14" (symbPinId 150) (portName "PN10") (portType INOUT))
        (port "N1" (symbPinId 151) (portName "VREF-") (portType INOUT))
        (port "N2" (symbPinId 152) (portName "CSI_D1N") (portType INOUT))
        (port "N3" (symbPinId 153) (portName "CSI_CKN") (portType INOUT))
        (port "N4" (symbPinId 154) (portName "CSI_D0N") (portType INOUT))
        (port "N5" (symbPinId 155) (portName "CSI_REX_T") (portType INOUT))
        (port "N6" (symbPinId 156) (portName "VDDCSI") (portType INOUT))
        (port "N7" (symbPinId 157) (portName "PA10") (portType INOUT))
        (port "N8" (symbPinId 158) (portName "PA2") (portType INOUT))
        (port "N9" (symbPinId 159) (portName "PG12") (portType INOUT))
        (port "N10" (symbPinId 160) (portName "PG10") (portType INOUT))
        (port "N11" (symbPinId 161) (portName "PG2") (portType INOUT))
        (port "N12" (symbPinId 162) (portName "PA15") (portType INOUT))
        (port "N13" (symbPinId 163) (portName "PN3") (portType INOUT))
        (port "N14" (symbPinId 164) (portName "PN11") (portType INOUT))
        (port "P1" (symbPinId 165) (portName "VSS_8") (portType INOUT))
        (port "P2" (symbPinId 166) (portName "CSI_D1P") (portType INOUT))
        (port "P3" (symbPinId 167) (portName "CSI_CKP") (portType INOUT))
        (port "P4" (symbPinId 168) (portName "CSI_D0P") (portType INOUT))
        (port "P5" (symbPinId 169) (portName "VDDA18C_SI") (portType INOUT))
        (port "P6" (symbPinId 170) (portName "PA14") (portType INOUT))
        (port "P7" (symbPinId 171) (portName "PA13") (portType INOUT))
        (port "P8" (symbPinId 172) (portName "PA8") (portType INOUT))
        (port "P9" (symbPinId 173) (portName "PG13") (portType INOUT))
        (port "P10" (symbPinId 174) (portName "PA0") (portType INOUT))
        (port "P11" (symbPinId 175) (portName "PB10") (portType INOUT))
        (port "P12" (symbPinId 176) (portName "PA7") (portType INOUT))
        (port "P13" (symbPinId 177) (portName "PN1") (portType INOUT))
        (port "P14" (symbPinId 178) (portName "VSS_9") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "STM32N645I0H3Q")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Arm Cortex-M55-based MCU, with ST Neural-ART Accelerator, H264 encoder, Neo-Chrom 2.5D GPU, 4.2 Mbytes contiguous SRAM")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/stm32n657a0.pdf")
    (property "symbolName1" "STM32N645I0H3Q")
)
