(part "SAM-M10Q"
    (packageRef "SAMM10Q")
    (interface
        (port "1" (symbPinId 1) (portName "GND_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "V_IO") (portType INOUT))
        (port "3" (symbPinId 3) (portName "V_BCKP") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND_2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND_3") (portType INOUT))
        (port "6" (symbPinId 6) (portName "GND_4") (portType INOUT))
        (port "7" (symbPinId 7) (portName "TIMEPULSE") (portType INOUT))
        (port "8" (symbPinId 8) (portName "SAFEBOOT_N") (portType INOUT))
        (port "9" (symbPinId 9) (portName "SDA") (portType INOUT))
        (port "10" (symbPinId 10) (portName "GND_5") (portType INOUT))
        (port "11" (symbPinId 11) (portName "GND_6") (portType INOUT))
        (port "12" (symbPinId 12) (portName "SCL") (portType INOUT))
        (port "13" (symbPinId 13) (portName "TXD") (portType INOUT))
        (port "14" (symbPinId 14) (portName "RXD") (portType INOUT))
        (port "15" (symbPinId 15) (portName "GND_7") (portType INOUT))
        (port "16" (symbPinId 16) (portName "GND_8") (portType INOUT))
        (port "17" (symbPinId 17) (portName "VCC") (portType INOUT))
        (port "18" (symbPinId 18) (portName "RESET_N") (portType INOUT))
        (port "19" (symbPinId 19) (portName "EXTINT") (portType INOUT))
        (port "20" (symbPinId 20) (portName "GND_9") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "u-blox")
    (property "Manufacturer_Part_Number" "SAM-M10Q")
    (property "Mouser_Part_Number" "N/A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/u-blox/SAM-M10Q?qs=vvQtp7zwQdOcUykyQtAdbA%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "- RF Receiver Galileo, GLONASS, GPS 1.575GHz, 1.602GHz -165dBm 400kbps On-Board, Patch Module")
    (property "Datasheet_Link" "https://content.u-blox.com/sites/default/files/documents/SAM-M10Q_IntegrationManual_UBX-22020019.pdf")
    (property "symbolName1" "SAM-M10Q")
)
