(part "ECMF2-40A100N6"
    (packageRef "ECMF240A100N6")
    (interface
        (port "1" (symbPinId 1) (portName "D+_TO_CONNECTOR") (portType INOUT))
        (port "2" (symbPinId 2) (portName "D-_TO_CONNECTOR") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND_2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D-_TO_IC") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D+_TO_IC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "155")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "ECMF2-40A100N6")
    (property "Mouser_Part_Number" "511-ECMF2-40A100N6")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/ECMF2-40A100N6?qs=Znm5pLBrcAJS%2FJmQqRCfmw%3D%3D")
    (property "Arrow_Part_Number" "ECMF2-40A100N6")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ecmf2-40a100n6/stmicroelectronics.html?utm_currency=USD&region=nac")
    (property "Description" "2 Line Common Mode Choke Surface Mount 100mA DCR 3Ohm (Typ) , -55C ~ 125C")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/ecmf2-40a100n6.pdf")
    (property "symbolName1" "ECMF2-40A100N6")
)
