(part "ANT-916-HETH"
    (packageRef "ANT916HETH")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "ANT-916-HETH")
    (property "Mouser_Part_Number" "712-ANT-916-HETH")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity-Linx-Technologies/ANT-916-HETH?qs=K5ta8V%252BWhtZA1YNNY7nYdQ%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Helical Antenna, Single Band, LPWAN / LoRaWAN, Internal/Embedded Mount, Through-Hole/Tab Mount, Solder, Omnidirectional, Single Port, Gain > 6 dBi")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=ant-916-hexx&DocType=Data%20Sheet&DocLang=English&PartCntxt=ANT-916-HETH&DocFormat=pdf")
    (property "symbolName1" "ANT-916-HETH")
)
