(part "PE4259-63"
    (packageRef "SOT65P210X110-6N")
    (interface
        (port "1" (symbPinId 1) (portName "RF1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "RF2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "CTRL") (portType INOUT))
        (port "5" (symbPinId 5) (portName "RFC") (portType INOUT))
        (port "6" (symbPinId 6) (portName "%CTRL_OR_VDD%") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Peregrine Semiconductor")
    (property "Manufacturer_Part_Number" "PE4259-63")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "SPDT High Power UltraCMOS 10 MHz3.0 GHz RF Switch")
    (property "Datasheet_Link" "https://www.psemi.com/pdf/datasheets/pe4259ds.pdf")
    (property "symbolName1" "PE4259-63")
)
