(part "CC3350ENJARSBR"
    (packageRef "QFN40P500X500X80-41N-D")
    (interface
        (port "1" (symbPinId 1) (portName "PA_LDO_OUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "RF_BG") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VDDA_IN1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VDDA_IN2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "HFXT_P/EXT") (portType INOUT))
        (port "7" (symbPinId 7) (portName "HFXT_M") (portType INOUT))
        (port "8" (symbPinId 8) (portName "COEX_GRANT") (portType INOUT))
        (port "9" (symbPinId 9) (portName "COEX_PRIORITY") (portType INOUT))
        (port "10" (symbPinId 10) (portName "COEX_REQ") (portType INOUT))
        (port "11" (symbPinId 11) (portName "UART_RTS") (portType INOUT))
        (port "12" (symbPinId 12) (portName "UART_CTS") (portType INOUT))
        (port "13" (symbPinId 13) (portName "UART_RX") (portType INOUT))
        (port "14" (symbPinId 14) (portName "UART_TX") (portType INOUT))
        (port "15" (symbPinId 15) (portName "ANT_SEL") (portType INOUT))
        (port "16" (symbPinId 16) (portName "GND_2") (portType INOUT))
        (port "17" (symbPinId 17) (portName "VIO") (portType INOUT))
        (port "18" (symbPinId 18) (portName "SDIO_CMD") (portType INOUT))
        (port "19" (symbPinId 19) (portName "SDIO_CLK") (portType INOUT))
        (port "20" (symbPinId 20) (portName "GND_3") (portType INOUT))
        (port "21" (symbPinId 21) (portName "SDIO_D3") (portType INOUT))
        (port "22" (symbPinId 22) (portName "SDIO_D2") (portType INOUT))
        (port "23" (symbPinId 23) (portName "SDIO_D1") (portType INOUT))
        (port "24" (symbPinId 24) (portName "SDIO_D0") (portType INOUT))
        (port "25" (symbPinId 25) (portName "GND_4") (portType INOUT))
        (port "26" (symbPinId 26) (portName "SWCLK") (portType INOUT))
        (port "27" (symbPinId 27) (portName "SWDIO") (portType INOUT))
        (port "28" (symbPinId 28) (portName "LOGGER") (portType INOUT))
        (port "29" (symbPinId 29) (portName "HOST_IRQ_WL") (portType INOUT))
        (port "30" (symbPinId 30) (portName "HOST_IRQ_BLE") (portType INOUT))
        (port "31" (symbPinId 31) (portName "DIG_LDO_OUT") (portType INOUT))
        (port "32" (symbPinId 32) (portName "VDD_MAIN_IN") (portType INOUT))
        (port "33" (symbPinId 33) (portName "NRESET") (portType INOUT))
        (port "34" (symbPinId 34) (portName "SLOW_CLK_IN") (portType INOUT))
        (port "35" (symbPinId 35) (portName "VPP_IN") (portType INOUT))
        (port "36" (symbPinId 36) (portName "FAST_CLK_REQ") (portType INOUT))
        (port "37" (symbPinId 37) (portName "GND_5") (portType INOUT))
        (port "38" (symbPinId 38) (portName "RF_A") (portType INOUT))
        (port "39" (symbPinId 39) (portName "PA_LDO_IN_1") (portType INOUT))
        (port "40" (symbPinId 40) (portName "PA_LDO_IN_2") (portType INOUT))
        (port "41" (symbPinId 41) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "CC3350ENJARSBR")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "CC3350ENJARSBR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/cc3350enjarsbr/texas-instruments?utm_currency=USD&region=nac")
    (property "Description" "Key Features  Wi-Fi 6 (802.11ax)  Bluetooth Low Energy 5.4 in CC33x1 devices  Companion IC to any processor or MCU host capable of running a TCP/IP stack  Integrated 2.4GHz and 5GHz PA for complete wireless solution with up to +20.5dBm output power.  Operating temperature: 40C to +105C  Application throughput up to 50Mbps Extended Features  Wi-Fi 6  2.4GHz and 5GHz, 20MHz, single spatial stream  MAC, baseband, and RF transceiver with support for IEEE 802.11 a/b/g/n/ax  OFDMA, t")
    (property "Datasheet_Link" "https://www.ti.com/lit/ds/symlink/cc3350.pdf?ts=1745530269962&ref_url=https%253A%252F%252Fwww.mouser.com%252F")
    (property "symbolName1" "CC3350ENJARSBR")
)
