(part "LM4670ITL_NOPB"
    (packageRef "BGA9C50P3X3_146X148X68")
    (interface
        (port "A1" (symbPinId 1) (portName "IN+") (portType INOUT))
        (port "A2" (symbPinId 2) (portName "GND_1") (portType INOUT))
        (port "A3" (symbPinId 3) (portName "VO1") (portType INOUT))
        (port "B1" (symbPinId 4) (portName "VDD") (portType INOUT))
        (port "B2" (symbPinId 5) (portName "PVDD") (portType INOUT))
        (port "B3" (symbPinId 6) (portName "GND_2") (portType INOUT))
        (port "C1" (symbPinId 7) (portName "IN-") (portType INOUT))
        (port "C2" (symbPinId 8) (portName "%SHUTDOWN%") (portType INOUT))
        (port "C3" (symbPinId 9) (portName "VO2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "LM4670ITL/NOPB")
    (property "Mouser_Part_Number" "595-LM4670ITL/NOPB")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/LM4670ITL-NOPB?qs=2k4gZbgf%2F9nVYKjbIJpyZw%3D%3D")
    (property "Arrow_Part_Number" "LM4670ITL/NOPB")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/lm4670itlnopb/texas-instruments")
    (property "Description" "Filterless High Efficiency 3W Switching Audio Amplifier")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/lm4670")
    (property "symbolName1" "LM4670ITL_NOPB")
)
