(part "74439324033"
    (packageRef "74439324033")
    (interface
        (port "1" (symbPinId 1) (portName "N1+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "N1-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Manufacturer_Name" "Wurth Elektronik")
    (property "Manufacturer_Part_Number" "74439324033")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "WE-XHMI SMT Power Inductor Size 4030; L = 3.3 H +/-20%; IR = 7.10 A; Isat = 8.2 A; RDCmax = 25.5 m")
    (property "Datasheet_Link" "https://www.we-online.com/catalog/datasheet/74439324033.pdf")
    (property "symbolName1" "74439324033")
)
