(part "SQA411CEJW-T1_GE3"
    (packageRef "SQA411CEJWT1_GE3")
    (interface
        (port "1" (symbPinId 1) (portName "D_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "D_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "G") (portType INOUT))
        (port "4" (symbPinId 4) (portName "S_1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D_3") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D_4") (portType INOUT))
        (port "7" (symbPinId 7) (portName "S_2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "D_5") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "SQA411CEJW-T1_GE3")
    (property "Mouser_Part_Number" "78-SQA411CEJW-T1_GE3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Semiconductors/SQA411CEJW-T1_GE3?qs=MyNHzdoqoQKvSQEfP%252BAPkA%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Automotive P-Channel 60 V (D-S) 175 C MOSFET")
    (property "Datasheet_Link" "https://www.vishay.com/en/product/63171/")
    (property "symbolName1" "SQA411CEJW-T1_GE3")
)
