(part "BM08B-SRSS-TB_LF__SN_"
    (packageRef "BM08BSRSSTBLFSN")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "9" (symbPinId 9) (portName "MP1") (portType INOUT))
        (port "10" (symbPinId 10) (portName "MP2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "JST (JAPAN SOLDERLESS TERMINALS)")
    (property "Manufacturer_Part_Number" "BM08B-SRSS-TB(LF)(SN)")
    (property "Mouser_Part_Number" "N/A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/JST-Commercial/BM08B-SRSS-TBLFSN?qs=QpmGXVUTftFK%2FkBkMXJr9A%3D%3D")
    (property "Arrow_Part_Number" "BM08B-SRSS-TB(LF)(SN)")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/bm08b-srss-tb-lf-sn/jst-manufacturing.html?utm_currency=USD&region=europe")
    (property "Description" "Connector: wire-board; socket; male; 1A; 50V; PIN: 8; SMT; 1mm; 1x8")
    (property "Datasheet_Link" "https://www.jst.com/wp-content/uploads/2021/03/eSR_SZ-new.pdf")
    (property "symbolName1" "BM08B-SRSS-TB_LF__SN_")
)
