(part "TFM201610ALC-R47MTAA"
    (packageRef "INDC2016X80N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Manufacturer_Name" "TDK")
    (property "Manufacturer_Part_Number" "TFM201610ALC-R47MTAA")
    (property "Mouser_Part_Number" "810-TFM201610ALCR47M")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TDK/TFM201610ALC-R47MTAA?qs=MLItCLRbWsy9rkE7tyNMeg%3D%3D")
    (property "Arrow_Part_Number" "TFM201610ALC-R47MTAA")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tfm201610alc-r47mtaa/tdk?region=nac")
    (property "Description" "Inductors for Power Circuits, for Consumer, Thin Film Metal, TFM201610ALC ,-40 to +125")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/DKDS41/DSANUWW0039576.pdf")
    (property "symbolName1" "TFM201610ALC-R47MTAA")
)
