(part "TXU0204BQAR"
    (packageRef "TXU0204BQAR")
    (interface
        (port "1" (symbPinId 1) (portName "VCCA") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "A2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "A3Y") (portType INOUT))
        (port "5" (symbPinId 5) (portName "A4Y") (portType INOUT))
        (port "6" (symbPinId 6) (portName "NC_1") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GND") (portType INOUT))
        (port "8" (symbPinId 8) (portName "OE") (portType INOUT))
        (port "9" (symbPinId 9) (portName "NC_2") (portType INOUT))
        (port "10" (symbPinId 10) (portName "B4") (portType INOUT))
        (port "11" (symbPinId 11) (portName "B3") (portType INOUT))
        (port "12" (symbPinId 12) (portName "B2Y") (portType INOUT))
        (port "13" (symbPinId 13) (portName "B1Y") (portType INOUT))
        (port "14" (symbPinId 14) (portName "VCCB") (portType INOUT))
        (port "15" (symbPinId 15) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TXU0204BQAR")
    (property "Mouser_Part_Number" "595-TXU0204BQAR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TXU0204BQAR?qs=QNEnbhJQKvZCd1v9XZcqJQ%3D%3D")
    (property "Arrow_Part_Number" "TXU0204BQAR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/txu0204bqar/texas-instruments?utm_currency=USD&region=europe")
    (property "Description" "TXU0204 is a 4-bit, dual-supply noninverting fixed direction voltage level translation device.")
    (property "Datasheet_Link" "https://www.ti.com/lit/ds/symlink/txu0204.pdf?ts=1625930454609")
    (property "symbolName1" "TXU0204BQAR")
)
