(part "MM8030-2610RJ3"
    (packageRef "MM80302610RJ3")
    (interface
        (port "1" (symbPinId 1) (portName "IN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "OUT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "MM8030-2610RJ3")
    (property "Mouser_Part_Number" "81-MM8030-2610RJ3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Electronics/MM8030-2610RJ3?qs=dnvuLCnOKpt0o1NKcCkttA%3D%3D")
    (property "Arrow_Part_Number" "MM8030-2610RJ3")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/mm8030-2610rj3/murata-manufacturing.html?utm_currency=USD&region=nac")
    (property "Description" "RF Connectors / Coaxial Connectors 250Vrms 0.07ohms 11GHZ")
    (property "Datasheet_Link" "https://www.murata.com/-/media/webrenewal/support/library/catalog/products/connector/o30e.ashx?la=en-sg&cvid=20230202042145000000")
    (property "symbolName1" "MM8030-2610RJ3")
)
