(part "TPS2121RUXT"
    (packageRef "TPS2121RUXT")
    (interface
        (port "1" (symbPinId 1) (portName "OUT_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "IN2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CP2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "OV2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "OV1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "PR1") (portType INOUT))
        (port "7" (symbPinId 7) (portName "IN1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "OUT_2") (portType INOUT))
        (port "9" (symbPinId 9) (portName "ST") (portType INOUT))
        (port "10" (symbPinId 10) (portName "ILIM") (portType INOUT))
        (port "11" (symbPinId 11) (portName "SS") (portType INOUT))
        (port "12" (symbPinId 12) (portName "GND") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS2121RUXT")
    (property "Mouser_Part_Number" "595-TPS2121RUXT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS2121RUXT?qs=l7cgNqFNU1i6abJCbO5ulQ%3D%3D")
    (property "Arrow_Part_Number" "TPS2121RUXT")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tps2121ruxt/texas-instruments.html?utm_currency=USD&region=nac")
    (property "Description" "Power Switch ICs - Power Distribution 2.7-22V, 56mG , 4.5A, Priority Power MUX with Seamless Switchover 12-VQFN-HR -40 to 125")
    (property "Datasheet_Link" "https://www.arrow.com/en/products/tps2121ruxt/texas-instruments")
    (property "symbolName1" "TPS2121RUXT")
)
