(part "LM4670SD_NOPB"
    (packageRef "SON50P300X300X80-9N")
    (interface
        (port "1" (symbPinId 1) (portName "%SHUTDOWN%") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-IN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "+IN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND_1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VO1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "GND_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VDD") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VO2") (portType INOUT))
        (port "9" (symbPinId 9) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "LM4670SD/NOPB")
    (property "Mouser_Part_Number" "595-LM4670SD/NOPB")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/LM4670SD-NOPB?qs=2k4gZbgf%2F9nNpTS8Wdbmrw%3D%3D")
    (property "Arrow_Part_Number" "LM4670SD/NOPB")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/lm4670sdnopb/texas-instruments?utm_currency=USD&region=nac")
    (property "Description" "Filterless High Efficiency 3W Switching Audio Amplifier")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/lm4670")
    (property "symbolName1" "LM4670SD_NOPB")
)
